insert into public.videos (title, slug, description, youtube_url, thumbnail_url, tags, featured, published_at) values
('Distributed Systems in 15 Minutes', 'distributed-systems-15-minutes', 'A compact explanation of core distributed systems concepts.', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'https://i.ytimg.com/vi/dQw4w9WgXcQ/maxresdefault.jpg', '{"distributed systems","architecture"}', true, '2026-03-01'),
('System Design: API Gateway Patterns', 'api-gateway-patterns', 'Practical API gateway design decisions for modern cloud stacks.', 'https://www.youtube.com/watch?v=ysz5S6PUM-U', 'https://i.ytimg.com/vi/ysz5S6PUM-U/maxresdefault.jpg', '{"system design","api"}', true, '2026-02-18');

insert into public.blog_posts (title, slug, excerpt, content, cover_image_url, tags, featured, published_at) values
('How I Scope Engineering Projects as a Solutions Engineer', 'scoping-engineering-projects', 'A practical framework for scoping projects with speed and confidence.', '## Why scope matters\nGreat scope aligns outcomes, risks, and constraints...', 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40', '{"career","solutions engineering"}', true, '2026-03-10');

insert into public.projects (name, slug, category, summary, description, github_url, demo_url, video_slug, image_url, featured, published_at) values
('LLM Ops Prompt Evaluator', 'llm-ops-prompt-evaluator', 'AI', 'Proof-of-understanding project for prompt evaluation and reliability.', 'A Learn Build Teach project where I implemented a prompt evaluation loop, tracked regression metrics, and documented tradeoffs in prompt strategy.', 'https://github.com/example/llm-ops-prompt-evaluator', 'https://example.com/prompt-evaluator', 'distributed-systems-15-minutes', 'https://images.unsplash.com/photo-1677442136019-21780ecad995', true, '2026-02-01'),
('Cloud Cost Guardrails', 'cloud-cost-guardrails', 'Cloud', 'Proof-of-understanding project for cloud governance and budgets.', 'A Learn Build Teach project that applies policy-as-code checks to enforce spend controls and document cloud architecture decisions.', 'https://github.com/example/cloud-cost-guardrails', 'https://example.com/cost-guardrails', 'api-gateway-patterns', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f', true, '2025-12-12');