insert into public.videos (title, slug, description, why_this_video_exists, category, youtube_url, thumbnail_url, tags, featured, published_at) values
('What Happens in a RAG Pipeline?', 'what-happens-in-a-rag-pipeline', 'A teaching-first walkthrough of retrieval, embeddings, ranking, and response generation.', 'I made this explainer to pressure-test my understanding of how retrieval-augmented generation actually works across retrieval, ranking, and answer synthesis.', 'AI/ML', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'https://i.ytimg.com/vi/dQw4w9WgXcQ/maxresdefault.jpg', '{"rag","llms","embeddings"}', true, '2026-03-21'),
('How Feature Stores Help AI Teams Move Faster', 'how-feature-stores-help-ml-teams-move-faster', 'A practical explanation of feature reuse, online vs. offline stores, and why this matters in production ML.', 'This video helps me turn a broad ML systems idea into a concrete explanation I can connect back to production tradeoffs.', 'AI/ML', 'https://www.youtube.com/watch?v=ysz5S6PUM-U', 'https://i.ytimg.com/vi/ysz5S6PUM-U/maxresdefault.jpg', '{"feature store","ml systems","production ml"}', true, '2026-02-18'),
('System Design: API Gateway Patterns', 'api-gateway-patterns', 'Practical API gateway design decisions for modern cloud and backend stacks.', 'I recorded this to make sure I could explain when API gateways help, when they add complexity, and how they fit into a real architecture.', 'Cloud', 'https://www.youtube.com/watch?v=jNQXAC9IVRw', 'https://i.ytimg.com/vi/jNQXAC9IVRw/maxresdefault.jpg', '{"system design","api gateway","backend"}', true, '2026-01-30');

insert into public.blog_posts (title, slug, excerpt, content, cover_image_url, tags, featured, published_at) values
('Why Teaching Forces Better Understanding', 'why-teaching-forces-better-understanding', 'The feedback loop I use to turn passive study into visible proof of learning.', '## Why I built this workflow\nIf I cannot explain a concept simply, I probably do not understand it deeply enough yet...', 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40', '{"learning","teaching","career"}', true, '2026-03-10');

insert into public.projects (name, slug, category, summary, description, github_url, demo_url, video_slug, image_url, featured, published_at) values
('LLM Ops Prompt Evaluator', 'llm-ops-prompt-evaluator', 'AI/ML', 'Proof-of-understanding project for prompt evaluation and reliability.', 'A Learn Build Teach project where I implemented a prompt evaluation loop, tracked regression metrics, and documented tradeoffs in prompt strategy.', 'https://github.com/example/llm-ops-prompt-evaluator', 'https://example.com/prompt-evaluator', 'what-happens-in-a-rag-pipeline', 'https://images.unsplash.com/photo-1677442136019-21780ecad995', true, '2026-02-01'),
('Event-Driven Integration Sandbox', 'event-driven-integration-sandbox', 'Cloud', 'A backend playground for learning APIs, queues, retries, and observability together.', 'A Learn Build Teach project that maps system design concepts into a hands-on sandbox with asynchronous processing, retries, and dashboarding.', 'https://github.com/example/event-driven-integration-sandbox', 'https://example.com/event-driven-sandbox', 'api-gateway-patterns', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f', true, '2025-12-12');
